/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttendeeDTO } from '../models/AttendeeDTO';
import { HttpFile } from '../http/http';

export class AnalyticsResponseDTO {
    /**
    * Total number of tickets sold
    */
    'totalTicketsSold': number;
    /**
    * Total sales amount
    */
    'totalSales': number;
    /**
    * List of events with attendees information
    */
    'attendeesList': Array<AttendeeDTO>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "totalTicketsSold",
            "baseName": "totalTicketsSold",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalSales",
            "baseName": "totalSales",
            "type": "number",
            "format": ""
        },
        {
            "name": "attendeesList",
            "baseName": "attendeesList",
            "type": "Array<AttendeeDTO>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalyticsResponseDTO.attributeTypeMap;
    }

    public constructor() {
    }
}
