/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BusinessConnectedAccount {
    /**
    * Account ID
    */
    'id': string;
    /**
    * Flag indicates account has been verified or not
    */
    'status': BusinessConnectedAccountStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BusinessConnectedAccountStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BusinessConnectedAccount.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum BusinessConnectedAccountStatusEnum {
    Pending = 'PENDING',
    VerificationRequired = 'VERIFICATION_REQUIRED',
    Connected = 'CONNECTED'
}

