/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BillingDetails } from '../models/BillingDetails';
import { Card } from '../models/Card';
import { HttpFile } from '../http/http';

export class CardList {
    'id': string;
    'object': string;
    'allowRedisplay': string;
    'billingDetails': BillingDetails;
    'card': Card;
    'created': number;
    'customer': any;
    'livemode': boolean;
    'metadata': any;
    'type': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "allowRedisplay",
            "baseName": "allow_redisplay",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingDetails",
            "baseName": "billing_details",
            "type": "BillingDetails",
            "format": ""
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "Card",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number",
            "format": ""
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "any",
            "format": ""
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CardList.attributeTypeMap;
    }

    public constructor() {
    }
}

