/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateStaffDto {
    /**
    * First name of the staff
    */
    'firstName': string;
    /**
    * Last name of the staff (optional)
    */
    'lastName'?: string;
    /**
    * Email address of the staff
    */
    'email': string;
    /**
    * Roles assigned to the staff as an array of ObjectIds
    */
    'roles'?: Array<string>;
    /**
    * OwnerId of the staff
    */
    'owner': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateStaffDto.attributeTypeMap;
    }

    public constructor() {
    }
}

