/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeviceEntity } from '../models/DeviceEntity';
import { HttpFile } from '../http/http';

export class DeviceAddResponse {
    /**
    * Status code of the response
    */
    'statusCode': number;
    /**
    * Device details
    */
    'data': DeviceEntity;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "number",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "DeviceEntity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeviceAddResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

