/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttendeeDTO } from '../models/AttendeeDTO';
import { HttpFile } from '../http/http';

export class EventDTO {
    /**
    * ID of the event
    */
    'eventId': string;
    /**
    * Name of the event
    */
    'eventName': string;
    /**
    * List of attendees for the event
    */
    'attendees': Array<AttendeeDTO>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventName",
            "baseName": "eventName",
            "type": "string",
            "format": ""
        },
        {
            "name": "attendees",
            "baseName": "attendees",
            "type": "Array<AttendeeDTO>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EventDTO.attributeTypeMap;
    }

    public constructor() {
    }
}
