/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserDetails } from '../models/UserDetails';
import { HttpFile } from '../http/http';

export class ReadingGoalResponse {
    'id': string;
    'userId': UserDetails;
    'visibility': string;
    'bookReadGoal': number;
    'noOffYear': number;
    'bookReadGoalCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "UserDetails",
            "format": ""
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "string",
            "format": ""
        },
        {
            "name": "bookReadGoal",
            "baseName": "bookReadGoal",
            "type": "number",
            "format": ""
        },
        {
            "name": "noOffYear",
            "baseName": "noOffYear",
            "type": "number",
            "format": ""
        },
        {
            "name": "bookReadGoalCount",
            "baseName": "bookReadGoalCount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReadingGoalResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

