/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReadingGoalResponse } from '../models/ReadingGoalResponse';
import { HttpFile } from '../http/http';

export class ReadingGoalResponseDTO {
    'data': ReadingGoalResponse;
    'isSuccess': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "ReadingGoalResponse",
            "format": ""
        },
        {
            "name": "isSuccess",
            "baseName": "isSuccess",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReadingGoalResponseDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

