/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Rating } from '../models/Rating';
import { HttpFile } from '../http/http';

export class Review {
    'id': string;
    'totalRatingCount': number;
    'rating': Array<Rating>;
    'totalRating': number;
    'averageRating': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalRatingCount",
            "baseName": "totalRatingCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "rating",
            "baseName": "rating",
            "type": "Array<Rating>",
            "format": ""
        },
        {
            "name": "totalRating",
            "baseName": "totalRating",
            "type": "number",
            "format": ""
        },
        {
            "name": "averageRating",
            "baseName": "averageRating",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Review.attributeTypeMap;
    }

    public constructor() {
    }
}

