/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PermissionResponseDto } from '../models/PermissionResponseDto';
import { HttpFile } from '../http/http';

export class RoleResponseDto {
    'id': string;
    'name': string;
    'description': string;
    'permissions': Array<PermissionResponseDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<PermissionResponseDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RoleResponseDto.attributeTypeMap;
    }

    public constructor() {
    }
}
