/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StoreDetailsPayloadDto {
    'storeName': string;
    'storeLogo': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "storeName",
            "baseName": "storeName",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeLogo",
            "baseName": "storeLogo",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StoreDetailsPayloadDto.attributeTypeMap;
    }

    public constructor() {
    }
}
