/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StripeResponse {
    'paymentId': string;
    'paymentIntent': string;
    'ephemeralKey': string;
    'customer': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "paymentId",
            "baseName": "paymentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentIntent",
            "baseName": "paymentIntent",
            "type": "string",
            "format": ""
        },
        {
            "name": "ephemeralKey",
            "baseName": "ephemeralKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StripeResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

