/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserAchievementResponse {
    'friend': boolean;
    'event': boolean;
    'book': boolean;
    'readingGoal': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "friend",
            "baseName": "friend",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "book",
            "baseName": "book",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "readingGoal",
            "baseName": "readingGoal",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserAchievementResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

