/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class VerificationLinkResponseDTO {
    /**
    * Verification link
    */
    'link': string;
    /**
    * Expiration when link will be invalid
    */
    'expires': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "expires",
            "baseName": "expires",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VerificationLinkResponseDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

